resources:
- name: chaos-loris-repo
  type: git
  source:
    uri: {{chaos-loris-repo}}
    branch: master

jobs:
- name: deploy-chaos-loris
  tasks:
  - name: deploy-chaos-loris
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: allomov/chaos-loris
          tag: "v0.1.5"
      inputs:
        - name: config-repo
      
      run:
        path: bash
        args: |
          -c
          ./mvnw clean package
